"""Stable machine-readable errors (plan §45). Adapters translate these; domain raises them."""

from enum import StrEnum


class ErrorCode(StrEnum):
    CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
    CAPABILITY_VERSION_NOT_FOUND = "CAPABILITY_VERSION_NOT_FOUND"
    CAPABILITY_ALREADY_EXISTS = "CAPABILITY_ALREADY_EXISTS"
    CAPABILITY_NOT_ELIGIBLE = "CAPABILITY_NOT_ELIGIBLE"
    CAPABILITY_REVOKED = "CAPABILITY_REVOKED"
    SKILL_PACKAGE_INVALID = "SKILL_PACKAGE_INVALID"
    BUNDLE_VALIDATION_FAILED = "BUNDLE_VALIDATION_FAILED"
    ROUTING_TIMEOUT = "ROUTING_TIMEOUT"
    POLICY_DENIED = "POLICY_DENIED"
    ARTIFACT_INTEGRITY_ERROR = "ARTIFACT_INTEGRITY_ERROR"
    CLIENT_INCOMPATIBLE = "CLIENT_INCOMPATIBLE"
    RATE_LIMITED = "RATE_LIMITED"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    ROUTE_RUN_NOT_FOUND = "ROUTE_RUN_NOT_FOUND"
    BUNDLE_NOT_FOUND = "BUNDLE_NOT_FOUND"
    OUTCOME_NOT_FOUND = "OUTCOME_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_TRANSITION_INVALID = "TASK_TRANSITION_INVALID"
    EXECUTOR_CONTRACT_VIOLATION = "EXECUTOR_CONTRACT_VIOLATION"
    MODEL_FAILURE = "MODEL_FAILURE"
    #: Transient provider failure (5xx, transport, timeout) — retryable.
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_MALFORMED_OUTPUT = "MODEL_MALFORMED_OUTPUT"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_PATH_INVALID = "WORKSPACE_PATH_INVALID"
    WORKSPACE_SNAPSHOT_NOT_FOUND = "WORKSPACE_SNAPSHOT_NOT_FOUND"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_ARGUMENT_INVALID = "TOOL_ARGUMENT_INVALID"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_REPLAY_INVALID = "APPROVAL_REPLAY_INVALID"
    AUTHORITY_EXPIRED = "AUTHORITY_EXPIRED"


class DomainError(Exception):
    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
